config/routes.rb
Rails.application.routes.draw do
  
get 'site_visitors/index'
root 'site_visitors#index'
resources :site_visitors
 
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/site_visitor.rb
class SiteVisitor < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/site_visitors_controller.rb
class SiteVisitorsController < ApplicationController
  before_action :set_site_visitor, only: [:show, :edit, :update, :destroy]

  # GET /site_visitors
  # GET /site_visitors.json
  def index
    @site_visitors = SiteVisitor.all
  end

  # GET /site_visitors/1
  # GET /site_visitors/1.json
  def show
  end

  # GET /site_visitors/new
  def new
    @site_visitor = SiteVisitor.new
  end

  # GET /site_visitors/1/edit
  def edit
  end

  # POST /site_visitors
  # POST /site_visitors.json
  def create
    @site_visitor = SiteVisitor.new(site_visitor_params)

    respond_to do |format|
      if @site_visitor.save
        format.html { redirect_to @site_visitor, notice: 'Site visitor was successfully created.' }
        format.json { render :show, status: :created, location: @site_visitor }
      else
        format.html { render :new }
        format.json { render json: @site_visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /site_visitors/1
  # PATCH/PUT /site_visitors/1.json
  def update
    respond_to do |format|
      if @site_visitor.update(site_visitor_params)
        format.html { redirect_to @site_visitor, notice: 'Site visitor was successfully updated.' }
        format.json { render :show, status: :ok, location: @site_visitor }
      else
        format.html { render :edit }
        format.json { render json: @site_visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /site_visitors/1
  # DELETE /site_visitors/1.json
  def destroy
    @site_visitor.destroy
    respond_to do |format|
      format.html { redirect_to site_visitors_url, notice: 'Site visitor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site_visitor
      @site_visitor = SiteVisitor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_visitor_params
      params.require(:site_visitor).permit(:name, :phonenumber)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site_visitors_helper.rb
module SiteVisitorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebSite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/site_visitors/_form.html.erb
<%= form_with(model: site_visitor, local: true) do |form| %>
  <% if site_visitor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(site_visitor.errors.count, "error") %> prohibited this site_visitor from being saved:</h2>

      <ul>
      <% site_visitor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :site_visitor_name %>
  </div>

  <div class="field">
    <%= form.label :phonenumber %>
    <%= form.text_field :phonenumber, id: :site_visitor_phonenumber %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/site_visitors/edit.html.erb
<h1>Editing Site Visitor</h1>

<%= render 'form', site_visitor: @site_visitor %>

<%= link_to 'Show', @site_visitor %> |
<%= link_to 'Back', site_visitors_path %>

app/views/site_visitors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Site Visitors</h1>

<table>
  <thead>
    <tr>
      <th>name</th>
      <th>Phonenumber</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @site_visitors.each do |site_visitor| %>
      <tr>
        <td><%= site_visitor.name %></td>
        <td><%= site_visitor.phonenumber %></td>
        <td><%= link_to 'Show', site_visitor %></td>
        <td><%= link_to 'Edit', edit_site_visitor_path(site_visitor) %></td>
        <td><%= link_to 'Destroy', site_visitor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Site Visitor', new_site_visitor_path %>

app/views/site_visitors/new.html.erb
<h1>New Site Visitor</h1>

<%= render 'form', site_visitor: @site_visitor %>

<%= link_to 'Back', site_visitors_path %>

app/views/site_visitors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>name:</strong>
  <%= @site_visitor.name %>
</p>

<p>
  <strong>Phonenumber:</strong>
  <%= @site_visitor.phonenumber %>
</p>

<%= link_to 'Edit', edit_site_visitor_path(@site_visitor) %> |
<%= link_to 'Back', site_visitors_path %>